cxx_library(
  name = 'tests',
  header_namespace = '',
  exported_headers = subdir_glob([
    ('', '*.h'),
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  visibility = [
    'PUBLIC',
  ],
  deps = [
    '//:sqlpp11',
  ],
)
