cxx_binary(
  name = 'count-of-count',
  header_namespace = '',
  srcs = [
    'count_of_count.cpp',
  ],
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:sqlpp11',
    '//tests:tests',
  ],
)

cxx_binary(
  name = 'max-of-max',
  header_namespace = '',
  srcs = [
    'max_of_max.cpp',
  ],
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:sqlpp11',
    '//tests:tests',
  ],
)
